#!/bin/csh

# Input files and output files
set dir=`dirname $1`
set base=`basename $1 .s`
set file=$dir/$base
# Preserve CWD
set base=`dirname $`

# Assemble to object file
sparc-linux-as -g -Asparc $file.s -o $file.o
# Link to ELF
sparc-linux-ld -dynamic-linker /lib/ld-uClibc.so.0 -e start $file.o $base/runtime/*.o $base/runtime/*/*.o  -lc -o $file
