#!/bin/bash

# List of test files
TEST_FILES=(
  "RcClobberTest.java"
  "RcArgumentTest.java"
  "RcEscapeTest.java"
  "RcValidPointerTest.java"
  "RcInvalidPointerTest.java"
  "DoubleDecrementTest.java"
  "CyclicGarbageTest.java"
  "MSBigMemoryTest.java"
  "UseAfterCopyTest.java"
)

for file in "${TEST_FILES[@]}"; do
  # Name without extension
  testName=$(basename -s .java "$file")

  # Build and move to top dir
  ./compile $1 $2 "tests/$file"
  ./assemble "tests/${testName}.s"
  mv "tests/${testName}" "${testName}"
done
