#!/bin/csh

# Build garbage collector tests
./compile tests/RcClobberTest.java
./assemble tests/RcClobberTest.s
mv tests/RcClobberTest RcClobberTest

./compile tests/RcArgumentTest.java
./assemble tests/RcArgumentTest.s
mv tests/RcArgumentTest RcArgumentTest
