#!/bin/csh

# Build garbage collector tests
./compile tests/RcClobberTest.java
./assemble tests/RcClobberTest.s
mv tests/RcClobberTest RcClobberTest

./compile tests/RcArgumentTest.java
./assemble tests/RcArgumentTest.s
mv tests/RcArgumentTest RcArgumentTest

./compile tests/RcEscapeTest.java
./assemble tests/RcEscapeTest.s
mv tests/RcEscapeTest RcEscapeTest

./compile tests/RcValidPointerTest.java
./assemble tests/RcValidPointerTest.s
mv tests/RcValidPointerTest RcValidPointerTest

./compile tests/RcInvalidPointerTest.java
./assemble tests/RcInvalidPointerTest.s
mv tests/RcInvalidPointerTest RcInvalidPointerTest